### ISSUE TITLE
Multiple OSC Message value not showing

### ISSUE THREAD

**Issue by enzyme69** [JPfeP/AddOSC#3]
The Multiple OSC Message can now be selected by index, which is nice. However, I noticed the value is not showing anymore on the panel:

![screen shot 2016-10-28 at 21 20 53](https://cloud.githubusercontent.com/assets/3952687/19803477/97efdf14-9d54-11e6-9164-f41ad587eab3.png)

It simply says: "Unknown".

I tried to access this property in Animation Nodes, and it says "Unknown". Wonder how to get to the indexed value...?

**Comment by enzyme69** [comment]
And also, if you are using Animation Nodes, wondering if there is a direct access to incoming OSC values, per message, or the one I am doing below is correct:

![screen shot 2016-10-28 at 21 59 03](https://cloud.githubusercontent.com/assets/3952687/19804406/d77e42d8-9d59-11e6-8a3b-3cd4fc599281.png)

I do still need to remap values.

**Comment by JPfeP** [comment]
Not sure what is happening. Beside the refresh problem of the GUI (sometimes updated only on the mouse movement over the panel), the reason of a Unknown value might be that the type of the message was not the one expected. Blender for instance will accept an integer if a float is expected but if the number is expressed as a string it won't be converted. May be the nodes used in AN do this implicitly. I will check this ASAP when I'm back from my vacation Friday. 

Do you see anything in the 'last OSC message' box ? If a list is received you should see all the items.

**Comment by JPfeP** [comment]
Hi, I found the problem about index > 0 and monitored value not updating. Indeed I introduced a last minute change last time before committing, causing the fault . I have not yet uploaded the fix but I will do soon this week-end. Currently trying to resolve the whole refresh problem.   

So it was not was I had in mind.
